project:
  type: website

website:
  title: "Clinicians who code"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - education.qmd
      - who-are-we.qmd
      - about.qmd
    logo: "/images/cwc-logo.png"

format:
  html:
    theme: 
      light: yeti
      dark: darkly
    css: styles.css
    toc: true



